name: Websplatter
url: http://vsiguero.github.io
description: A personal trip to web programming technologies

permalink: /:categories/:year/:month/:day/:title.html
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']